set -g default-terminal "screen-256color"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5


bind -r m resize-pane -Z 

set -g mouse on #enables scrolling

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session
# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'joshmedeski/t-smart-tmux-session-manager'
#set -g @plugin 'jimeh/tmux-themepack'

# set -g @plugin 'tmux-plugins/tmux-resurrect' #presistent sessions
# set -g @plugin 'tmux-plugins/tmux-continuum' #saves sessions every 15mins
# set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'

set -g @t-fzf-prompt '  '

set -g @catppuccin_flavour 'macchiato' # latte, frappe, macchiato, mocha

set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_status_enable "yes"
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_fill "all"

set -g @catppuccin_window_current_text "#{b:pane_current_path}" # use "#W" for application instead of directory

# set -g @catppuccin_window_left_separator " █"
set -g @catppuccin_window_left_separator " █"
# set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_right_separator "█"
set -g @catppuccin_window_status_icon_enable "yes"

set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_status_modules_right 'host directory application session date_time'
set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M"
set -g @catppuccin_application_icon '󰲋'
set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_right_separator " "

set -g @catppuccin_window_left_separator_inverse "yes"
set -g @catppuccin_status_right_separator_inverse "yes"

set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text '#{pane_current_path}'

set -g @catppuccin_icon_window_last "󰖰"
set -g @catppuccin_icon_window_current "󰖯"
set -g @catppuccin_icon_window_zoom "󰁌"
set -g @catppuccin_icon_window_mark "󰃀"
set -g @catppuccin_icon_window_silent "󰂛"
set -g @catppuccin_icon_window_activity "󰖲"
set -g @catppuccin_icon_window_bell "󰂞"

# set -g @catppuccin_l_left_separator ""
# set -g @catppuccin_l_right_separator ""
# set -g @catppuccin_r_left_separator ""
# set -g @catppuccin_r_right_separator ""
# set -g @catppuccin_no_patched_fonts_theme_enabled on

# Initialize TMUX plugin manager (KEEP AT BOTTOM)
run '~/.config/tmux/plugins/tpm/tpm'
